name: Clean cache

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: opengrabeso/clean-cache@v2.1.0
        with:  
          post: true
          keep: 0
